---
name: pre-commit

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: install and execute hadolint
        shell: bash
        run: |
          HADOLINT_URL="https://github.com/hadolint/hadolint/\
          releases/download/v2.12.0/hadolint-Linux-x86_64"
          wget -O hadolint ${HADOLINT_URL}
          chmod +x hadolint
          sudo mv hadolint /bin/hadolint
      - uses: pre-commit/action@v3.0.1
